config/routes.rb
Naturesoft::HotelNewdiscoveryVn::Engine.routes.draw do
  root to: "home#index"
  get "trang-ve-chung-toi.html" => "home#about_us", as: :about_us
  match "/404", :to => "errors#not_found", :via => :all
end
Naturesoft::Articles::Engine.routes.draw do
  get "bai-viet/blog-du-lich.html" => "articles#listing", as: :blog_listing
  get "bai-viet/blog-du-lich/:blog_id-:title" => "articles#detail", as: :blog_detail
  get "faq.html" => "articles#faq", as: :faq
end
Naturesoft::Areas::Engine.routes.draw do
  get "khach-san-theo-dia-diem.html" => "areas#listing", as: :area_listing
end
Naturesoft::Contacts::Engine.routes.draw do
  get "trang-lien-he.html" => "contacts#contact", as: :contacts
  post "lien-he.html" => "contacts#send_message"
end
Naturesoft::Galleries::Engine.routes.draw do
  get "thu-vien.html" => "galleries#listing", as: :gallery_listing
  get "thu-vien/:gallery_id-:title.html" => "galleries#detail", as: :gallery_detail
end
Naturesoft::Core::Engine.routes.draw do
  devise_scope :user do
    get "dang-nhap.html" => "/naturesoft/users/sessions#new", as: :login
    get "dang-ky.html" => "/naturesoft/users/registrations#new", as: :register
  end
  get "xac-thuc-email.html" => "users#confirmable_email", as: :confirmable_email
  get "quen-mat-khau.html" => "users#forgot_password", as: :forgot_password
  get "cap-nhat-mat-khau-moi.html" => "users#reset_password", as: :reset_password
  get "thanh-vien/ho-so.html" => "users#admin_area", as: :admin_area
  post "thanh-vien/ho-so.html" => "users#admin_area"
  get "thanh-vien/lich-su.html" => "users#order_history", as: :order_history
  get "thanh-vien/yeu-thich.html" => "users#wish_list", as: :wish_list
  get "thanh-vien/cai-dat.html" => "users#settings", as: :settings  
  post "thanh-vien/cai-dat.html" => "users#settings"
  post "thanh-vien/update-newsletter.html" => "users#update_newsletter", as: :update_newsletter
end
Naturesoft::Hotels::Engine.routes.draw do
  resources :reviews
  resources :event_orders
  resources :orders do
    collection do
      get "chi-tiet-thong-tin-dat-phong.html" => "orders#invoice", as: :invoice
    end
  end
  resources :wish_lists do
    collection do
      get 'add_item'
    end
  end
  get "danh-sach-khach-san/dang-luoi.html" => "hotels#hotels_grid", as: :hotels_grid
  get "danh-sach-khach-san/dang-danh-sach.html" => "hotels#hotels_list", as: :hotels_list
  get "khach-san/:hotel_id-:title.html" => "hotels#detail", as: :hotel_detail
  get "trang-khuyen-mai.html" => "events#hotel_listing", as: :events_hotel_listing
  get "dang-ky-nhanh.html" => "quick_orders#quick_booking", as: :quick_bookings
  post "dang-ky-nhanh.html" => "quick_orders#quick_booking"
  get "danh-gia-khach-san-:id.html" => "hotels#reviews_list", as: :hotel_reviews_list
end
Naturesoft::Newsletters::Engine.routes.draw do
  get "dang-ky-nhan-tin.html" => "newsletters#add_email", as: :newsletters
  post "dang-ky-nhan-tin.html" => "newsletters#add_email"
end

app/controllers/naturesoft/hotel_newdiscovery_vn/errors_controller.rb
module Naturesoft
    module HotelNewdiscoveryVn
        class ErrorsController < Naturesoft::FrontendController
            def not_found
                render(:status => 404)
            end
        end
    end
end

app/controllers/naturesoft/hotel_newdiscovery_vn/home_controller.rb
module Naturesoft
  module HotelNewdiscoveryVn
    class HomeController < Naturesoft::FrontendController
      def index
      end
      def about_us
      end
    end
  end
end

app/helpers/naturesoft/hotel_newdiscovery_vn/application_helper.rb
module Naturesoft
  module HotelNewdiscoveryVn
    module ApplicationHelper
    end
  end
end

app/views/naturesoft/areas/areas/listing.html.erb

<% menu = Naturesoft::Menus::Menu.where(id: params["hotel_list_id"]).first %>

<section class="parallax-window" data-parallax="scroll" data-image-src="/frontend/img/hotels_bg.jpg" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
            <h1><%= @current_menu.name %></h1>
            <p><%= @current_menu.description %></p>
        </div>
    </div>
</section>
<!-- End Section -->

<div id="position">
    <div class="container">
        <ul>
            <li><%= link_to "Trang Chủ", naturesoft_hotel_newdiscovery_vn.root_path %></li>
            <li><%= @current_menu.name if @current_menu.present? %></li>
        </ul>
    </div>
</div>
<!-- End Position -->

<div class="container margin_60">

    <div class="main_title">
        <h2>Danh sách địa điểm</h2>
        <p></p>
    </div>

    <div class="row">
        <% @main_areas.each do |item| %>
        <div class="col-md-4 col-sm-6 wow zoomIn" data-wow-delay="0.1s">
            <div class="tour_container">
                <div class="img_container">
                    <a href="<%= menu.url + '?area_id=' + item.id.to_s %>">
                        <% if item.image.present? %>
                        <%= image_tag(item.image.big, size: "800x533", alt: "", class: "img-responsive") %>
                        <% else %>
                        <%= image_tag("/frontend/img/no-img.png", alt: "", class: "img-responsive") %>
                        <% end %>
                        <div class="short_info">
                            <i class="icon_set_1_icon-6"></i>Khách Sạn<span class="price">(Có <%= Naturesoft::Hotels::Hotel.count_hotels_by_area(item).count %> khách sạn)</span>
                        </div>
                    </a>
                </div>
                <div class="tour_title">
                    <h3><strong><%= link_to item.name, menu.url + '?area_id=' + item.id.to_s %></strong></h3>
                </div>
            </div>
            <!-- End box tour -->
        </div>
        <!-- End col-md-4 -->
        <% end %>
    </div>
</div>
<!-- End container -->

app/views/naturesoft/areas/backend/nsmodules/areas_list/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
        <label class="control-label" ><%= t(:style) %> <span class='text-danger'>*</span></label>
        <select class="select2" name="options[style]">
            <option <%= "selected" if options["style"] == "default" %> value="default">default</option>
        </select>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
        <label class="control-label" ><%= t(:menu_id) %> <span class='text-danger'>*</span></label>
        <div class="">
            <% menu = Naturesoft::Menus::Menu.where(id: options["menu_id"]).first %>
            <% selected = options_for_select([[menu.name,menu.id]], menu.id) if !menu.nil? %>
            <%= select_tag("options[menu_id]",
              selected,
              {
                class: "select2-ajax required",
                include_blank: "none",
                "data-url": naturesoft_menus.select2_backend_menus_path(parent_id: "all"),
              }
            ) %>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
        <label class="control-label" ><%= t(:areas) %> <span class='text-danger'>*</span></label>
        <div class="">
            <% areas = Naturesoft::Areas::Area.where(id: options["areas"]) %>
            <% selected = options_for_select((areas.map {|c| [c.name, c.id]}), options["areas"]) if !areas.nil? %>
            <%= select_tag("options[areas][]",
              selected,
              {
                class: "select2-ajax required",
                include_blank: "none",
                multiple: "multiple",
                "data-url": naturesoft_areas.select2_backend_areas_path,
              }
            ) %>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
        <label class="control-label" ><%= t(:description) %> </label>
        <div class="">
          <%= text_area_tag "options[description]", options["description"], class: "form-control" %>
        </div>
    </div>
  </div>
</div>

app/views/naturesoft/articles/articles/detail.html.erb
<section class="parallax-window" data-parallax="scroll" data-image-src="/frontend/img/bg_blog.jpg" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
            <h1>BLOG DU LỊCH</h1>
            <p>Ridiculus sociosqu cursus neque cursus curae ante scelerisque vehicula.</p>
        </div>
    </div>
</section>
<!-- End section -->

<div id="position">
    <div class="container">
        <ul>
            <li><%= link_to "Trang Chủ", naturesoft_hotel_newdiscovery_vn.root_path %></li>
            <% menu = Naturesoft::Menus::Menu.get_by_type(["articles::listing"]).first %>
            <% if menu.present? %>
                <li class="active_menu" rel="<%= menu.id %>"><%= link_to menu.name, menu.url %></li>
            <% end %>
            <li><%= "Chi tiết" %></li>
        </ul>
    </div>
</div>
<!-- End position -->

<div class="container margin_60">
    <div class="row">

        <div class="col-md-9">
            <div class="box_style_1">
                <div class="post nopadding">
                    <%= image_tag(@article.image_url.lager, alt: "786x310", class: "img-responsive") %>
                    <div class="post_info clearfix">
                        <div class="post-left">
                            <ul>
                                <li><i class="icon-calendar-empty"></i> Đăng ngày <span><%= @article.created_at.strftime("%d/%m/%Y") %></span></li>
                            <li><i class="icon-inbox-alt"></i> Chuyên mục: <% @article.categories.each_with_index do |c,index| %><% if index == 0 %><%= c.name %><% end %><% if index > 0 %><%= ", " + c.name %><% end %><% end %></li>
                                <li><i class="icon-tags"></i> Nhãn:
                                <% if !@article.get_tags.empty? %>
                                    <% len = @article.get_tags.length %>
                                    <% @article.get_tags.each_with_index do |tag,i| %>
                                        <% if i+1==len %>
                                            <%= link_to(tag,'') %>
                                        <% else %>
                                            <%= link_to(tag,'') %>,
                                        <% end %>
                                    <% end %>
                                <% end %>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <h2><%= @article.title %></h2>
                    <div class="text-justify">
                        <%= @article.content.html_safe %>
                    </div>
                </div>
                <!-- end post -->
            </div>
            <!-- end box_style_1 -->
        </div>
        <!-- End col-md-8-->

        <aside class="col-md-3 add_bottom_30">

            <%= render "/modules/blog_sidebar" %>

        </aside>
        <!-- End aside -->

    </div>
    <!-- End row-->
</div>
<!-- End container -->

app/views/naturesoft/articles/articles/faq.html.erb
<section class="parallax-window" data-parallax="scroll" data-image-src="<%= !@current_menu.nil? ? @current_menu.image.default : nil %>" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
            <h1><%= @current_menu.name %></h1>
            <p><%= @current_menu.description %></p>
        </div>
    </div>
</section>
<!-- End section -->

<div id="position">
    <div class="container">
        <ul>
            <li><%= link_to "Trang Chủ", naturesoft_hotel_newdiscovery_vn.root_path %></li>
            <li><%= @current_menu.name if @current_menu.present? %></li>
        </ul>
    </div>
</div>
<!-- Position -->

<div class="container margin_60">
    <div class="row">
        <aside class="col-lg-3 col-md-3" id="sidebar">
            <div class="theiaStickySidebar">
                <div class="box_style_cat" id="faq_box">
                    <ul id="cat_nav">
                        <% @category.children.each do |item| %>
                        <li><a href="#tab_<%= item.id %>"><i class="icon_set_1_icon-95"></i><%= item.name %></a></li>
                        <% end %>
                    </ul>
                </div>
            </div>
            <!--End sticky -->
        </aside>
        <!--End aside -->
        <div class="col-lg-9 col-md-9" id="faq">
            <% @category.children.each do |item| %>
                <% if item.articles.count != 0 %><h3 class="nomargin_top"><%= item.name %></h3><% end %>
    
                <div class="panel-group" id="tab_<%= item.id %>">
                    <% item.articles.each_with_index do |article,index| %>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#art_<%= item.id %>_<%= index %>" href="#collapseOne_art_<%= item.id %>_<%= index %>"><%= article.title %><i class="indicator icon-plus pull-right"></i></a>
                                </h4>
                            </div>
                            <div id="collapseOne_art_<%= item.id %>_<%= index %>" class="panel-collapse collapse">
                                <div class="panel-body text-justify">
                                    <%= article.content.html_safe %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
                <!-- End panel-group -->
            <% end %>

        </div>
        <!-- End col lg-9 -->
    </div>
    <!-- End row -->
</div>
<!-- End container -->

app/views/naturesoft/hotel_newdiscovery_vn/modules/_blog_sidebar.html.erb
<div class="widget">
    <div class="">
        <%= form_tag("", method: "get", class: "input-group") do %>
            <input type="text" name="key" value="<%= params[:key] if params[:key].present? %>" class="form-control" placeholder="Tìm kiếm...">
            <span class="input-group-btn">
            <button class="btn btn-default" type="submit" style="margin-left:0;"><i class="icon-search"></i></button>
            </span>
        <% end %>
    </div>
    <!-- /input-group -->
</div>
<!-- End Search -->
<hr>
<div class="widget" id="cat_blog">
    <%= position("hotel_newdiscovery_vn::categories-blog-sidebar") %>
</div>
<!-- End widget -->

<hr>

<div class="widget">
    <h4>Có thể bạn quan tâm</h4>
    <ul class="recent_post">
        <% Naturesoft::Articles::Article.get_recent_posts.each do |item| %>
        <li>
            <i class="icon-calendar-empty"></i> <%= item.created_at.strftime("%d/%m/%Y") %>
            <div><%= link_to item.title, naturesoft_articles.blog_detail_path(blog_id: item.id, title: url_friendly(item.title)) %></div>
        </li>
        <% end %>
    </ul>
</div>
<!-- End widget -->

app/views/naturesoft/hotel_newdiscovery_vn/modules/_common_scripts.html.erb
<!-- Common scripts -->
<%= javascript_include_tag "/frontend/js/jquery-1.11.2.min.js" %>
<%= javascript_include_tag "/frontend/js/common_scripts_min.js" %>
<%= javascript_include_tag "/frontend/js/functions.js" %>

app/views/naturesoft/hotel_newdiscovery_vn/modules/_flash_messages_popup.html.erb
<% colors = {"notice" => "info", "alert" => "danger"} %>                    
<% flash.each do |key, value| %>
<script>
    $(document).ready(function() {
        if (!$(".site-alert-box").length) {
            swal({
                title: '',
                text: '<%= value %>',
                confirmButtonText: "<%= t('ok') %>",
                allowOutsideClick: true,
            });
        }
    });
</script>
<% end %>

app/views/naturesoft/hotel_newdiscovery_vn/modules/_hotel_overlay.html.erb
<div id="toTop"></div><!-- Back to top button --> 
<div id="overlay"></div><!-- Mask on input focus -->

app/views/naturesoft/hotel_newdiscovery_vn/modules/_nav_tabs_admin_area.html.erb
<nav>
    <ul>
        <li class="<%= 'tab-current' if params[:action] == 'admin_area' %>">
            <%= link_to('<span>Thông tin thành viên</span>'.html_safe, admin_area_path, class: "icon-profile") %>
        </li>
        <li class="<%= 'tab-current' if params[:action] == 'order_history' %>">
            <%= link_to('<span>Lịch sử đặt phòng</span>'.html_safe, order_history_path, class: "icon-booking") %>
        </li>
        <li class="<%= 'tab-current' if params[:action] == 'wish_list' %>">
            <%= link_to('<span>Khách sạn yêu thích</span>'.html_safe, wish_list_path, class: "icon-wishlist") %>
        </li>
        <li class="<%= 'tab-current' if params[:action] == 'settings' %>">
            <%= link_to('<span>Cài đặt</span>'.html_safe, settings_path, class: "icon-settings") %>
        </li>
    </ul>
</nav>

app/views/naturesoft/users/admin_area.html.erb
<section class="parallax-window" data-parallax="scroll" data-image-src="/frontend/img/admin_top.jpg" data-natural-width="1400" data-natural-height="470">
<div class="parallax-content-1">
    <div class="animated fadeInDown">
        <h1>Welcome, <%= current_user.display_name %></h1>
    </div>
</div>
</section>
<!-- End section -->

<div id="position">
<div class="container">
    <ul>
        <li><%= link_to "Trang Chủ", naturesoft_hotel_newdiscovery_vn.root_path %></li>
        <li>Tài khoản thành viên</li>
    </ul>
</div>
</div>
<!-- End Position -->

<div class="margin_60 container">
<div id="" class="tabs">
    <%= render '/modules/nav_tabs_admin_area' %>
    <div class="content">
      
        <section id="section-1" class="content-current">
            <div class="row">
                <div class="col-md-8 col-sm-6">
                    <h4>Thông tin của bạn</h4>
                    <ul id="profile_summary">
                        <li>Email <span><a href="mailto:<%= current_user.email %>"></a><%= current_user.email %></span></li>
                        <li>Họ <span><%= current_user.first_name %></span></li>
                        <li>Tên <span><%= current_user.last_name %></span></li>
                        <li>Số điện thoại <span><%= current_user.phone %></span></li>
                        <li>Ngày sinh <span><%= current_user.birthdate.strftime("%d/%m/%Y") if !current_user.birthdate.nil? %></span></li>
                        <li>Địa chỉ <span><%= current_user.address %></span></li>
                        <li>Mã Zip <span><%= current_user.zip %></span></li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-6">
                    <img src="<%= user_image_src(current_user.image.profile) %>" alt="Image" class="img-responsive styled profile_pic">
                    </p>
                </div>
            </div>
            <!-- End row -->

            <div class="divider"></div>

            <%= form_for(:user, url: admin_area_path, html: {class: "validate", multipart: true}) do |f| %>
            <div class="row">
                <div class="col-md-12">
                    <h4>Cập nhật thông tin</h4>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Họ & đệm</label>
                        <%= f.text_field :first_name, class: "form-control required", placeholder: "Cập nhật họ & tên đệm.....", value: (current_user.first_name if current_user.first_name.present?) %>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Tên</label>
                        <%= f.text_field :last_name, class: "form-control required", placeholder: "Cập nhật tên.....", value: (current_user.last_name if current_user.last_name.present?) %>
                    </div>
                </div>
            </div>
            <!-- End row -->

            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Số điện thoại</label>
                        <%= f.text_field :phone, class: "form-control required", placeholder: "Cập nhật số điện thoại.....", value: (current_user.phone if current_user.phone.present?) %>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Ngày sinh <small>(dd/mm/yyyy)</small></label>
                        <%= f.text_field :birthdate, class: "form-control required", placeholder: "Cập nhật ngày sinh.....", value: (current_user.birthdate if current_user.birthdate.present?) %>
                    </div>
                </div>
            </div>
            <!-- End row -->

            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h4>Cập nhật địa chỉ</h4>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <%= f.text_field :address, class: "form-control required", placeholder: "Cập nhật địa chỉ.....", value: (current_user.address if current_user.address.present?) %>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                        <label>Mã bưu chính (Zip Code)</label>
                        <%= f.text_field :zip, class: "form-control", placeholder: "Cập nhật mã Zip.....", value: (current_user.zip if current_user.zip.present?) %>
                    </div>
                </div>
            </div>
            <!-- End row -->

            <hr>
            <h4>Cập nhật hình đại diện</h4>
            <div class="form-inline upload_1">
                <div class="form-group">
                    <input type="file" name="user[image]" id="js-upload-files" multiple>
                </div>
            </div>

            <hr>
            <button type="submit" class="btn_1 green">Cập nhật thông tin</button>
            <% end %>
        </section>
        <!-- End section 1 -->

        </div>
        <!-- End content -->
    </div>
    <!-- End tabs -->
</div>
<!-- end container -->

app/views/naturesoft/users/forgot_password.html.erb
<section id="hero" class="login">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <div id="login">
                    <div class="text-center"><img src="/frontend/img/logo_sticky.png" alt="Image" data-retina="true"></div>
                    <hr>
                    <%= form_for(:user, :url => password_path(:user)) do |f| %>
                        <p>Nhập email đã đăng ký để lấy lại mật khẩu.</p>
                        <div class="form-group">
                            <label>Email</label>
                            <%= f.email_field :email, autofocus: true, class: "form-control email required", placeholder: "Nhập email tại đây..." %>
                        </div>
                        <button class="btn_full">Lấy lại mật khẩu</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/naturesoft/users/login.html.erb
<section id="hero" class="login">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <div id="login">
                    <div class="text-center"><img src="/frontend/img/logo_sticky.png" alt="Image" data-retina="true"></div>
                    <hr>
                    <%= form_for(:user, :url => session_path(:user)) do |f| %>
                        <div class="row">
                            <div class="col-md-6 col-sm-6 login_social">
                                <a href="" class="btn btn-primary btn-block"><i class="icon-facebook"></i> Facebook</a>
                            </div>
                            <div class="col-md-6 col-sm-6 login_social">
                                <a href="" class="btn btn-info btn-block "><i class="icon-google"></i>Google</a>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="login-or">
                        <hr class="hr-or"><span class="span-or">hoặc</span></div>

                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" class="form-control" placeholder="Nhập email tại đây...">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu</label>
                            <input type="password" class="form-control" placeholder="Nhập mật khẩu tại đây...">
                        </div>
                        <p class="small">
                            <%= link_to "Quên mật khẩu", naturesoft.forgot_password_path %>
                        </p>
                        <button type="submit" class="btn_full">Đăng nhập</button>
                        <!--<%= link_to "Đăng nhập", naturesoft.admin_area_path, class: "btn_full" %>-->
                        <%= link_to "Đăng ký", naturesoft.register_path, class: "btn_full_outline" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/naturesoft/users/settings.html.erb
<section class="parallax-window" data-parallax="scroll" data-image-src="/frontend/img/admin_top.jpg" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
            <h1>Welcome, <%= current_user.display_name %></h1>
            <p>Ridiculus sociosqu cursus neque cursus curae ante scelerisque vehicula.</p>
        </div>
    </div>
</section>
<!-- End section -->

<div id="position">
    <div class="container">
        <ul>
            <li><%= link_to "Trang Chủ", naturesoft_hotel_newdiscovery_vn.root_path %></li>
            <li>Tài khoản thành viên</li>
        </ul>
    </div>
</div>
<!-- End Position -->
    
<div class="margin_60 container">
    <div id="tabs" class="tabs">
        <%= render '/modules/nav_tabs_admin_area' %>
        <div class="content">
            
            
                <section id="section-4" class="content-current">
                    <%= render "naturesoft/hotel_newdiscovery_vn/modules/flash_messages" %>
                    
                    <%= form_for(:user, url: settings_path, html: {class: "validate", multipart: true}) do |f| %>
                        <h4>Thay đổi mật khẩu</h4>
                        <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Mật khẩu cũ</label>
                                        <input class="form-control required" name="user[current_password]" id="current_password" type="password">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Mật khẩu mới</label>
                                        <input class="form-control" name="user[password]" id="password" type="password">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nhập lại mật khẩu mới</label>
                                        <input class="form-control" name="user[password_confirmation]" id="password_confirmation" type="password">
                                    </div>
                                </div>
                        </div>
                        <button type="submit" class="btn_1 green">Thay đổi mật khẩu</button>
                    <% end %>
                    
                    <br /><br /><br />
                    <!-- End row -->
                    
                    <h4>Cài đặt nhận tin mới</h4>
                    <%= form_for(:user, url: update_newsletter_path, html: {class: "validate", multipart: true}) do |f| %>
                        <div class="row">                        
                            <div class="col-md-6 col-sm-6">
                                <table class="table table-striped options_cart">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <i class="icon_set_1_icon-6"></i>
                                            </td>
                                            <td>Nhận tin mới của khách sạn yêu thích</td>
                                            <td>
                                                <!--< form_for(:user, url: settings_path, html: {class: "newsletter_enabled"}) do |f| %>-->
                                                <input type="hidden" name="user[newsletter_enabled]" value="false">
                                                <label class="switch-light switch-ios pull-right">
                                                    <input <%= "checked" if current_user.newsletter_enabled %> type="checkbox" value="true" name="user[newsletter_enabled]" id="option_2">
                                                    <span>
                                                        <span>Không</span>
                                                        <span>Có</span>
                                                    </span>
                                                    <a></a>
                                                </label>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <button type="submit" class="btn_1 green">Lưu thay đổi</button>
                    <% end %>
                    <!-- End row -->
                    
                </section>
                <!-- End section 4 -->
            
        </div>
        <!-- End content -->
    </div>
    <!-- End tabs -->
</div>
<!-- end container -->